version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - vi-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci

      - save_cache:
          key: vi-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run: npm run style
      - run: npm run lint

      - run: npm run build:prod
      - run: npm run test:nowatch

      - run:
          name: Tar && Gzip compiled app
          command: tar zcf dist.tar.gz dist/Wige-Dev
      - store_artifacts:
          path: dist.tar.gz
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
